version: '3.8'

services:
  llava-vision:
    build:
      context: .
      dockerfile: Dockerfile.llava
    container_name: llava-vision
    ports:
      - "8000:8000"
    volumes:
      - ./static/images:/app/images:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s